# Service ID
boost_hot_water:
  # Service name
  name: Boost Hot Water
  # Service description
  description: Boost hot water for a specified time period.
  
  # Target selection
  target:
    entity:
      domain: water_heater
      integration: badnest

  # Fields
  fields:
    time_period:
      name: Time Period
      description: Duration in minutes to boost hot water for.
      required: false
      default: 30
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: minutes
          mode: slider
          step: 1

    boost_mode:
      name: Boost Mode
      description: Whether to enable (true) or disable (false) boost mode.
      required: true
      selector:
        boolean:

# Service ID
cancel_boost_hot_water:
  # Service name
  name: Cancel Hot Water Boost
  # Service description
  description: Cancel the current hot water boost.
  
  # Target selection
  target:
    entity:
      domain: water_heater
      integration: badnest
